version: "3.9"

volumes:
  pg_data:

services:
  db:
    image: postgres:15.6-alpine
    container_name: auth-service-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DBNAME=auth_service
    ports:
      - "54321:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
